
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://github.com/foundry/Specs.git'


target 'TestOtherApp' do
    #  pod 'TestKit/Core', :path => '../TestKit'

pod 'TestKit/Models' #, :git => 'https://github.com/foundry/TestKit.git', :branch => 'protobufs'
pod 'TestKit/Views' #, :git => 'https://github.com/foundry/TestKit.git',  :branch => 'protobufs'
  # pod 'TestKit/Protobuf'  #,path => '../TestKit'

end
