
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://github.com/foundry/Specs.git'


target 'TestOtherApp' do
    #  pod 'TestKit/Core', :path => '../TestKit'

   pod 'TestKit/Models' 
   pod 'TestKit/Views' 
  # pod 'TestKit/Protobuf'  #,path => '../TestKit'

end
