
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://github.com/foundry/Specs.git'


target 'TestKitDemoApp' do
   # pod 'TestKit/Core',   :path => '../'

   pod 'TestKit/Models', :path => '../'
   pod 'TestKit/Views',  :path => '../'
  # pod 'TestKit/Protobuf'  #,path => '../'

end
